name: vint_deployment
channels:
- pytorch
- conda-forge
dependencies:
- python=3.8.5
- cudatoolkit=11.
- torchvision
- numpy
- matplotlib
- pyyaml
- rospkg
- opencv
- prettytable
- wandb
- einops
- vit-pytorch
- pip:
  - torch
  - torchvision
  - efficientnet_pytorch
  - warmup_scheduler
  - diffusers==0.11.1
  - huggingface_hub==0.25.2